### ISSUE TITLE
Update for new 1.0 API

### ISSUE THREAD

**Issue by cvan** [mdn/webvr-tests#3]
https://hacks.mozilla.org/2016/03/introducing-the-webvr-1-0-api-proposal/
https://mozvr.com/webvr-spec/

**Comment by chrisdavidmills** [comment]
I have the 1.0 API in my sights; I'll need to update the demos and the MDN docs. I wanted to wait until we had support in Nightly/Canary; when are they likely to land? Do you think that's a good idea, or should I move sooner?

**Comment by cvan** [comment]
> I wanted to wait until we had support in Nightly/Canary; when are they likely to land? Do you think that's a good idea, or should I move sooner?

Support for v1.0 has been in Brandon Jones' [Chromium builds](https://webvr.info/get-chrome/) since March. And it's shipping to Canary [very soon](https://twitter.com/Tojiro/status/729731821143916545).

Kip informed me today that we're very close with v1.0 support in Nightly. Patches far along, and builds will be passed around by end of the week.

**Comment by chrisdavidmills** [comment]
Good to know, thanks! In that case, I'll start preparing to document it this week.
